"""added time and nullable to comment on moviecomments

Revision ID: 016daa84ffb3
Revises: 3fe2b295d694
Create Date: 2021-05-07 03:17:21.606702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016daa84ffb3'
down_revision = '3fe2b295d694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moviecomment', sa.Column('date_posted', sa.String(length=32), nullable=False))
    op.alter_column('moviecomment', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moviecomment', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('moviecomment', 'date_posted')
    # ### end Alembic commands ###
