"""voting on movie comments

Revision ID: 92f67ed9ad75
Revises: 016daa84ffb3
Create Date: 2021-05-07 09:57:21.829728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f67ed9ad75'
down_revision = '016daa84ffb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moviecomment', sa.Column('up_votes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moviecomment', 'up_votes')
    # ### end Alembic commands ###
