"""testing something - no foreign keys

Revision ID: f0c2e195b0ab
Revises: ec97f56b59a5
Create Date: 2021-05-05 08:27:38.003896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c2e195b0ab'
down_revision = 'ec97f56b59a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('usertowatch_movie_id_fkey', 'usertowatch', type_='foreignkey')
    op.drop_constraint('usertowatch_user_id_fkey', 'usertowatch', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('usertowatch_user_id_fkey', 'usertowatch', 'user', ['user_id'], ['id'])
    op.create_foreign_key('usertowatch_movie_id_fkey', 'usertowatch', 'movie', ['movie_id'], ['id'])
    # ### end Alembic commands ###
